name: torgo
version: 1.3.1
summary: A Logo interpreter written in Java.
description: A Logo interpreter written in Java.
grade: stable

confinement: strict

apps:
  torgo:
    command: bin/wrapper
    plugs: [home, x11, opengl]

parts:
  torgo-mvn:
    plugin: maven
    source: .
    maven-options:
      - -DskipTests
    stage-packages:
      - fontconfig-config
      - openjdk-8-jre
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
  # torgo-dep:
  #   plugin: dump
  #   source: ../build/target
  #   organize:
  #     lib: jar/lib
  #   after:
  #     - torgo-mvn
  #   snap: [lib]
  torgo-files:
    plugin: dump
    source: .
    organize:
      ../build/wrapper: bin/
