name: torgo
version: 1.7.0
summary: A Logo interpreter written in Java.
description: A Logo interpreter written in Java.
grade: stable

confinement: strict

apps:
  torgo:
    command: bin/wrapper
    plugs: [home, x11, opengl, network, unity7]

parts:
  torgo:
    plugin: maven
    source: .
    maven-options:
      - -DskipTests=true
    stage-packages:
      - fontconfig-config
      - default-jdk
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
    stage:
      - -lib/x86_64-linux-gnu/libdbus-1**
    prime:
      - -lib/x86_64-linux-gnu/libdbus-1**
    after:
      - desktop-gtk2
#    after: [desktop-glib-only]
    organize:
      ../build/target/lib: jar/lib
      ../build/wrapper: bin/
#      ../build/torgo-mime.xml: usr/share/mime/packages/torgo-mime.xml
