name: torgo
version: 1.0.6
summary: A Logo interpreter written in Java.
description: A Logo interpreter written in Java.

confinement: strict

#license: LICENSE
#icon: src/main/resources/torgo-256x256.png

apps:
  torgo:
    command: bin/wrapper
    plugs: [home, x11, opengl]

parts:
  torgo-mvn:
    plugin: maven
    source: .
    stage-packages:
      - fontconfig-config
      - openjdk-8-jre
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
  torgo-dep:
    plugin: copy
    files:
      ../../torgo-mvn/build/target/lib: jar/lib
    after:
      - torgo-mvn
  wrapper:
      plugin: make
      source: .
