name: torgo
version: 1.0.7
summary: A Logo interpreter written in Java.
description: A Logo interpreter written in Java.

confinement: strict

apps:
  torgo:
    command: bin/wrapper
    plugs: [home, x11, opengl]

parts:
  torgo-mvn:
    plugin: maven
    source: .
    maven-options:
      - -DskipTests
    stage-packages:
      - fontconfig-config
      - openjdk-8-jre
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
  torgo-dep:
    plugin: copy
    files:
      ../../torgo-mvn/build/target/lib: jar/lib
    after:
      - torgo-mvn
  torgo-files:
    plugin: copy
    files:
      wrapper: bin/wrapper
